### PR TITLE
Do not display payments that fall below Liquid network minimum payment limit of 1,000 sats

### LINKED ISSUE #59: Wrong limits when scaning a LNURL
The warning message is with a wrong limit

image

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Fixes #59 

This PR addresses unit conversion issues on payment limits & prevents payments that fall below Liquid network minimum payment limit of 1000 sats to be shown to the user.

### CODE REVIEW

File: lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart [hunk 1]
```diff
@@ -16,6 +17,10 @@ Future<LNURLPageResult?> handleWithdrawRequest(
   BuildContext context,
   LnUrlWithdrawRequestData requestData,
 ) async {
+  if (requestData.maxWithdrawable.toInt() ~/ 1000 < liquidMinimumPaymentAmountSat) {
+    throw Exception("Payment is below Liquid network limits, $liquidMinimumPaymentAmountSat sats.");
```
Comment (roeierez) [inline lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart:21]: I wouldn't use teh term "liquid" in error messages to the user. Perhaps just "... bellow network limits..."

File: lib/utils/constants.dart [hunk 2]
```diff
@@ -0,0 +1 @@
+const liquidMinimumPaymentAmountSat = 1000;
```
Comment (roeierez) [inline lib/utils/constants.dart:1]: Don't we expose that in the sdk? Sounds like it needs to be there.

File: lib/routes/lnurl/payment/lnurl_payment_page.dart [hunk 3]
```diff
@@ -127,17 +128,21 @@ class LNURLPaymentPageState extends State<LNURLPaymentPage> {
...
                       children: <TextSpan>[
                         TextSpan(
                           text: texts.lnurl_fetch_invoice_min(
                             currencyState.bitcoinCurrency.format(
-                              (widget.data.minSendable.toInt() ~/ 1000),
+                              max(
+                                liquidMinimumPaymentAmountSat,
+                                max(
+                                  context.read<LnUrlCubit>().state.limits?.send.minSat.toInt() ?? 0,
+                                  widget.data.minSendable.toInt() ~/ 1000,
```
Comment (roeierez) [inline lib/routes/lnurl/payment/lnurl_payment_page.dart:143]: What is the difference between the two values here?

**Review by roeierez — CHANGES_REQUESTED** [review]

File: lib/routes/lnurl/payment/lnurl_payment_page.dart (hunk 3 above)
Comment (erdemyerebasmaz) [reply lib/routes/lnurl/payment/lnurl_payment_page.dart:143]: > What is the difference between the two values here?

@roeierez 
- [data.minSendable](https://github.com/lnurl/luds/blob/luds/06.md#pay-to-static-qrnfclink) is the minimum amount the LN service is willing to receive.

- `Limits` on `LightningPaymentLimitsResponse` is either normal or reverse submarine swap limits returned from Boltz service.

Both values can be below 1000 sats.

File: lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart (hunk 1 above)
Comment (erdemyerebasmaz) [reply lib/routes/lnurl/withdraw/lnurl_withdraw_handler.dart]: Done 817b727cfcb2e82e6ce658b7a86fbc11769017e9

File: lib/utils/constants.dart (hunk 2 above)
Comment (roeierez) [reply lib/utils/constants.dart:1]: Yes, I agree. We need to fill that gap in the sdk.

Comment (roeierez) [reply lib/utils/constants.dart:1]: Seems like we can get this value from `fetchLightningLimits` sdk function

Comment (erdemyerebasmaz) [reply lib/utils/constants.dart:1]: Addressed on child PR
- Fetch lightning limits on initializing LnUrlCubit ac992dc
- Rely on LnUrlState limits when validating payments 3ce88b9

File: lib/cubit/lnurl/lnurl_cubit.dart [hunk 4]
```diff
@@ -12,7 +15,19 @@ class LnUrlCubit extends Cubit<LnUrlState> {
...
   final BreezSDKLiquid _liquidSdk;
 
-  LnUrlCubit(this._liquidSdk) : super(LnUrlState.initial());
+  LnUrlCubit(this._liquidSdk) : super(LnUrlState.initial()) {
+    _initializeLnUrlCubit();
+  }
+
+  void _initializeLnUrlCubit() {
+    late final StreamSubscription streamSubscription;
+    streamSubscription = _liquidSdk.walletInfoStream.listen(
```
Comment (roeierez) [inline lib/cubit/lnurl/lnurl_cubit.dart:24]: NIT: Can use first() instead of creating a stream subscription.

File: lib/routes/create_invoice/create_invoice_page.dart [hunk 5]
```diff
@@ -74,23 +93,51 @@ class CreateInvoicePageState extends State<CreateInvoicePage> {
...
-        key: _formKey,
-        child: Padding(
-          padding: const EdgeInsets.fromLTRB(16.0, 0, 16.0, 40.0),
-          child: Scrollbar(
-            child: SingleChildScrollView(
-              child: Column(
-                mainAxisSize: MainAxisSize.max,
-                crossAxisAlignment: CrossAxisAlignment.start,
-                children: [
+      body: FutureBuilder<LightningPaymentLimitsResponse>(
```
Comment (roeierez) [inline lib/routes/create_invoice/create_invoice_page.dart:104]: Perhaps a stream builder is more appropriate here instead of maintaining a future?

File: lib/routes/create_invoice/create_invoice_page.dart [hunk 6]
```diff
@@ -63,6 +68,20 @@ class CreateInvoicePageState extends State<CreateInvoicePage> {
         }
       },
     );
+    _fetchLightningLimits();
+  }
+
+  void didChangeAppLifecycleState(AppLifecycleState state) {
+    if (state == AppLifecycleState.resumed) {
+      _fetchLightningLimits();
```
Comment (roeierez) [inline lib/routes/create_invoice/create_invoice_page.dart:76]: I think it is better to handle these refreshes automatically from within the bloc.
In c-breez we use FGBGEvents at the bloc level to refresh data on resume.

Comment (roeierez) [reply lib/routes/create_invoice/create_invoice_page.dart:76]: Also perhaps we can instantiate the LNurlCubit only around the pages uses it? I don't know how much effort needed to achieve it though.

File: lib/cubit/lnurl/lnurl_cubit.dart [hunk 7]
```diff
@@ -12,7 +15,19 @@ class LnUrlCubit extends Cubit<LnUrlState> {
...
+      (walletInfo) {
+        fetchLightningLimits();
```
Comment (roeierez) [inline lib/cubit/lnurl/lnurl_cubit.dart:26]: The fetchLightningLimits is in LnurlCubit. Do we use the limits also on regular lightning payments?

**Review by roeierez — CHANGES_REQUESTED** [review]

File: lib/cubit/lnurl/lnurl_cubit.dart (hunk 4 above)
Comment (erdemyerebasmaz) [reply lib/cubit/lnurl/lnurl_cubit.dart:24]: Done 124bc7f591b34f0b01efc9685e6df23d1c6b0821

File: lib/routes/create_invoice/create_invoice_page.dart (hunk 6 above)
Comment (erdemyerebasmaz) [reply lib/routes/create_invoice/create_invoice_page.dart:76]: > Also perhaps we can instantiate the LNurlCubit only around the pages uses it? I don't know how much effort needed to achieve it though.

It's achievable but let's address these in scope of another PR. I'm creating the issues.

File: lib/cubit/lnurl/lnurl_cubit.dart (hunk 7 above)
Comment (erdemyerebasmaz) [reply lib/cubit/lnurl/lnurl_cubit.dart:26]: > The fetchLightningLimits is in LnurlCubit. Do we use the limits also on regular lightning payments?

Yes, we should. It'll be addressed in scope of another PR.

File: lib/routes/create_invoice/create_invoice_page.dart (hunk 6 above)
Comment (erdemyerebasmaz) [reply lib/routes/create_invoice/create_invoice_page.dart:76]: https://github.com/breez/l-breez/issues/67

File: lib/routes/create_invoice/create_invoice_page.dart (hunk 5 above)
Comment (erdemyerebasmaz) [reply lib/routes/create_invoice/create_invoice_page.dart:104]: Yes, but this approach is more reliable with apps current state.

File: lib/app/routes/routes.dart [hunk 8]
```diff
@@ -69,18 +72,27 @@ Route? onGenerateRoute({
...
+                      child: const ReceiveChainSwapPage(),
+                    ),
                     settings: settings,
                   );
                 case SendChainSwapPage.routeName:
                   return FadeInRoute(
-                    builder: (_) => SendChainSwapPage(
-                      btcAddressData: settings.arguments as BitcoinAddressData?,
+                    builder: (_) => BlocProvider(
+                      create: (BuildContext context) => paymentLimitsCubit,
```
Comment (roeierez) [inline lib/app/routes/routes.dart:92]: If the cubit is instantiated globally then no reason to wrap it arround specific pages.
The idea was to create it per page so it will be "live" onlh during the page lifycycle and dispose it once the page exits.
I think either use it in the global blocs list or wrap on specific pages with create/dispose

**Review by roeierez — CHANGES_REQUESTED** [review]
Looks good. Small change requested

File: lib/app/routes/routes.dart (hunk 8 above)
Comment (erdemyerebasmaz) [reply lib/app/routes/routes.dart]: PaymentLimitsCubit is now created per page: [Fix PaymentLimitsCubit initialization](https://github.com/breez/l-breez/pull/63/commits/98ef3385a1015fe64fc5758c01e84b3b3d135260)

File: lib/cubit/payment_limits/payment_limits_cubit.dart [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+import 'package:flutter_breez_liquid/flutter_breez_liquid.dart';
+import 'package:flutter_fgbg/flutter_fgbg.dart';
+import 'package:hydrated_bloc/hydrated_bloc.dart';
+import 'package:l_breez/cubit/payment_limits/payment_limits_state.dart';
+import 'package:l_breez/utils/exceptions.dart';
+import 'package:logging/logging.dart';
+
+export 'payment_limits_state.dart';
+
+class PaymentLimitsCubit extends Cubit<PaymentLimitsState> {
```
Comment (roeierez) [inline lib/cubit/payment_limits/payment_limits_cubit.dart:14]: I think we should override here the onClose functino and close the fgbgevents stream.
This bloc is created on each page creation and the bloc framework calls the close function when the page is disposed.

**Review by roeierez — APPROVED** [review]
LGTM! please check my last comment before merging.

File: lib/cubit/payment_limits/payment_limits_cubit.dart (hunk 9 above)
Comment (erdemyerebasmaz) [reply lib/cubit/payment_limits/payment_limits_cubit.dart:16]: Done.
[Close foreground/background event notifier stream on close()](https://github.com/breez/l-breez/pull/63/commits/45b424eec85be97797f6d8e81bc944f7fc1decc1)
